### ISSUE TITLE
🌟[EPIC] Storybook as Atomic Design

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/ocelot-future#1]
## 🌟EPIC

We want to set the design from vue2 to vue3 and replace the styleguide with the Storybook

## 🤖ToDos

For Login-Page:
- [ ] 🚀[Feature] create atom for input element (ex. of usage: Email, password, ...)
- [ ] 🚀[Feature] create atom for standard button (ex. of usage: Login-Button, show/hide passwords-Button, ...)
- [ ] 🚀[Feature] create molecul for password input and show/hide button
- [ ] 🚀[Feature] create atom for links
- [ ] 🚀[Feature] create atom for language switch
- [ ] 🚀[Feature] create atom for the logo image
- [ ] 🚀[Feature] create organism for the login
- [ ] 🚀[Feature] create layout of the login
 
For header:
- [ ] 🚀[Feature] create atom for logo
- [ ] 🚀[Feature] create atom for Page-Link
- [ ] 🚀[Feature] create atom for Icon-Link
- [ ] 🚀[Feature] create organism for Profil button

For static pages:
- [ ] 🚀[Feature] create atom for Headedline
- [ ] 🚀[Feature] create atom for fix text
